### ISSUE TITLE
很好

### ISSUE THREAD

**Issue by dooqu** [xiongziliang/webrtc_apm#1]
很用心的项目

**Comment by xia-chu** [comment]
可惜现在as和ndk更新了 应该编译不过了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 静静的黎明 <notifications@github.com&gt;
发送时间: 2020年3月24日 12:33
收件人: xiongziliang/webrtc_apm <webrtc_apm@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xiongziliang/webrtc_apm] 很好 (#1)





 
很用心的项目

**Comment by dooqu** [comment]
是的，退到16版本的ndk编译通过的，赞

**Comment by xia-chu** [comment]
谢谢反馈！
